### ISSUE TITLE
A -no-color cli parameter to suppress the ANSI color codes in jsure output

### ISSUE THREAD

**Issue by nickgibbon** [berke/jsure#1]
When redirecting the output of jsure to a file, to a vim quick-fix window, or to any other non-shell destination the output from jsure contains many ANSI color codes. It would be useful to be able to suppress these codes for non-shell output destinations.

**Comment by berke** [comment]
Fixed in 1.0.4.

**Comment by nickgibbon** [comment]
Many thanks for the awesomely quick response.
